---
title: "Hatena2009-03-24"
---

hatena

```
<body>
*1237877428*Djangoでurlタグを使ったら謎のエラー
urlタグを使うと下の1や2の書き方をする代わりに3の書き方ができる。1の書き方は「現在表示しているURLは何か」を意識しないといけなくて、もしそのURLが変わったならば適切に../の数を変更しないとリンク切れになる可能性がある。2の書き方は「このアプリケーションが提供されているURL」を意識する必要があって、たとえば「http://example.com/programmers_nightmare/」で提供していたのを「http://programmers_nightmare.com/」での提供に変えた場合には書き直す必要がある。でもまあ1よりは変更頻度が低いのでまだまし。3の方法は「そのページを表示する関数」を指定してそこから逆算でURLを求めるので1や2ではリンク切れになるようなシチュエーションでも修正が必要ない。

>||
1: <a href="../../new_game/{{ id }}/">start new game</a>
2: <a href="/programmers_nightmare/new_game/{{ id }}/">start new game</a>
3: <a href="{% url programmers_ightmare.views.new_game id %}">start new game</a>
||<

という便利な機能なので使ってみようとしたのだけども、まだエラーメッセージがわかりにくいので戸惑った。

<a href='http://djangoproject.jp/doc/ja/1.0/ref/templates/builtins.html#ttag -url'>組み込みタグ／フィルタリファレンス &#8212; Django v1.0 documentation</a>

** まったく関係ない物を探しに行っているように見える
まず{% url new_game id %}と書いてみて最初にぶつかったのは下記のエラー。

>>
Caught an exception while rendering: Tried download_file in module programmers_nightmare.views. Error was: 'module' object has no attribute 'download_file'
<<

download_fileって！{% url new_game id %}って書いてあるのになんでそれを探しに行っている！

これはdownload_fileってのがどこで出現するのか調べてみると割と簡単にわかる。たとえばurls.pyでURLとビューのマッピングを指定する際に下のように文字列して指定している場合、いままでは/download/foobar/とかにアクセスしたときに初めて"download_file"という名前の関数を探しに行って「見つかりません」というエラーになっていたんだけども、urlタグを使うと「ビューからURLへ」の対応表を作る関係上全部のビューが定義済である必要がある。

>||
    (r'^new_game/(?P<key>\d+)/$', 'new_game'),
    (r'^download/(?P<key>\d+)/$', 'download_file'),
||<

なので、urls.pyからまだ中身を定義していない行をコメントアウトするか、views.pyで空のビューを定義してやればいい。

>||
def download_file(request, key):
    raise NotImplementedError
||<

** settings.new_gameを探しているエラー

>>
Caught an exception while rendering: Reverse for 'settings.programmers_nightmare.views.new_game' with arguments '('',)' and keyword arguments '{}' not found.
<<


settingsというよけいなプレフィックスがついて検索に失敗している。<a href='http://djangoproject.jp/doc/ja/1.0/topics/http/urls.html#naming-url-patterns'>URLパターンに名前を付ける</a>などを試してみたけど解決しない。google-app-patchの使っているurlsauto.pyが悪さをしているんじゃないか、とかもしかしてurlタグの実装との相性が悪いのか、とか思って調べてみた。urlタグは「与えられた引数で検索してみて見つからなかった場合にSETTINGS_MODULEのピリオド以前を付け加えて再検索する」という設計になっている。つまり、なぞのsettingsがついているけども単純に「検索が失敗した」と言っているだけ。

>|python|
    try:
        url = reverse(self.view_name, args=args, kwargs=kwargs)
    except NoReverseMatch:
        project_name = settings.SETTINGS_MODULE.split('.')[0]
        try:
            url = reverse(project_name + '.' + self.view_name,
                          args=args, kwargs=kwargs)
        except NoReverseMatch:
||<

改めてエラーログを見てみると、ああなるほど。変数idが未定義(=空文字列)なのでパターンにマッチしなかったんだ。それを修正したら問題なく動いた。

>>
Caught an exception while rendering: Reverse for 'settings.programmers_ightmare.views.new_game' with arguments <strong>'('',)'</strong> and keyword arguments '{}' not found.
<<

「変数が未定義の時は空文字列を返す」というテンプレートの挙動って割と罠なので、「そんな変数はないよ！」って例外を投げるStrictモードをつけたい気分なのだけど
<a href='http://djangoproject.jp/doc/ja/1.0/ref/templates/api.html#id6'>無効な値の扱い</a>によれば「Admin サイトのテンプレートをはじめとする多くのテンプレートは、実在しない値を呼び出しても何も出力しないという動作を前提に作られています。」ということなのでそうもいかないようだ。


まあurlタグがこけたら引数の変数名をtypoしていないか、ちゃんと期待した値が入っているか、を確認するのがいいのだろう。

*1237895547*家事(買い出し)
セブンイレブンにいって黒砂糖かりんとうをかい、その後イトーヨーカドーに行って黒砂糖かりんとうが安いことに凹み、73円の納豆を買い、その後ローソンの100円ショップに行ったら納豆が50円引きだった。


そういうわけで賞味期限が今日までの納豆が9パックあります。納豆ご飯以外の消費方法を調べねば。

<a href='http://cookpad.com/recipe/106926'>納豆スパ by monemaruku [クックパッド] 簡単おいしいみんなのレシピが40万品</a>
<a href='http://cookpad.com/recipe/437989'>納豆のカリカリチーズ焼き by 東雲Ａ [クックパッド] 簡単おいしいみんなのレシピが40万品</a>


カフェインのドーピングでやる気が出ると聞いたのでインスタントコーヒーを買ってきた。

*1237914302*[TopCoder] Single Round Match 437 (Div2/250point)
「数字を10進法で表現したときに、何種類の数字があるか答えなさい」という問題。sumはtoolboxからコピペした。accumulateくらいコピペしないでも書けるようにならないといけないか。あと0ULLってのはどうかと思った、T(0)でいいんじゃないのか。

久しぶりに一瞬で解ける問題だった。それとも最近ずっとスランプだった僕のプログラミングスキルが戻ってきつつあるのだろうか。coding time: 0:02:30.041, Passed System Test, 248.08points

>|cpp|
template<typename T>
T sum(vector<T> xs){
  return accumulate(xs.begin(), xs.end(), 0ULL);
}; 

class TheBeauty {
public:
  int find(int n) {
    vector<int> b(10);
    while(n){
      b[n % 10] = 1;
      n /= 10;
    }
    return sum(b);
  }
}
||<

*1237915040*[TopCoder] Single Round Match 437 (Div2/500point)
「整数nを10進法表記にして、k回数字の入れ替えを行ってつくることのできる最大の値は何か」という問題。ただし0で始まる数字を作ってはいけない。それが避けられない場合は-1を返せ、とのこと。

for文で前置インクリメントを使ってないのはよくないな。あと最後で最大の値を検索しているけど、setはソートされてるんじゃないのか。

coding time: 0:26:30.942, Passed System Test, 305.56 points
  	
>|cpp|
vector<int> to_vec(int n){
  vector<int> result;
  while(n){
    result.insert(result.begin(), n % 10);
    n /= 10;
  }
  
  return result;
}

vector<int> swap(vector<int> n, int i, int j){
  // n is a copy
  swap(n[i], n[j]);
  return n;
}

int to_int(vector<int> xs){
  int result = 0;
  for(size_t i=0; i < xs.size(); i++){
    result = result * 10 + xs[i];
  }
  return result;
}

class TheSwap {
public:
  int findMax(int n, int k) {
    vector<int> xs = to_vec(n);
    size_t N = xs.size();
    if(N == 1) return -1;
    set<int> cur;
    cur.insert(n);
    set<int> next;
    typedef set<int>::iterator siter;
    for(size_t times=0; times < k; times++){
      for(siter iter=cur.begin(), end=cur.end(); iter != end; iter++){
	int n = *iter;
	vector<int> xs = to_vec(n);
	for(size_t i=0; i<N; i++){
	  for(size_t j=i+1; j<N; j++){
	    vector<int> new_xs = swap(xs, i, j);
	    if(new_xs[0] != 0){
	      next.insert(to_int(new_xs));
	    }
	  }
	}
      }
      if(next.empty()) return -1;
      cur = next;
      next.clear();
    }
    int result = 0;
    for(siter iter=cur.begin(), end=cur.end(); iter != end; iter++){
      if(*iter > result){
	result = *iter;
      }
    }
    return result;
  }
}
||<

*1237915884*[TopCoder] Single Round Match 437 (Div2/1000point)
久しぶりに時間が十分余ったので1000点問題にも挑戦。「1からスタートして与えられた整数nまで何回の操作でたどり着けるかこたえなさい。やっていい操作は
- 1増やす
- 1減らす(元の値が1より大きい場合のみ)
- 累乗する(たとえば元の値が2なら4とか8とか16に変える)
の3つ」


単純に計算すると当然3の累乗で可能性が膨らんで行って発散するので「すでに出た数字は探索しない(最短ではないから)」「ゴールを超えた数字はdecrementで戻ってくるしかないので、powerはギリギリ超えるところまで」「ゴールを超えている数はインクリメントしない」という枝刈りを入れたのだけど、それでもまだ枝刈りが足りなくて、10分前から大急ぎでdistanceって変数を入れて「一番ゴール近い数とゴールの距離よりもゴールより上にはなれている数は最短になり得ないので探索しない」「終盤でpowerが使われなくなったらあとはincrementやdecrementでにじり寄るだけなので+distanceして終了」ってやったけど手元でreal 0m4.153s。タイムアウトで全然ダメ。

>|cpp|
  int count(long long goal) {
    typedef unsigned long long ULL;
    const ULL MAX_ULL = 18446744073709551615ULL;
    set<ULL> cur;
    cur.insert(1);
    set<ULL> next;
    set<ULL> used;
    ULL distance = goal - 1;
    typedef set<ULL>::iterator siter;
    int result = 0;
    if(goal == 1) return 0;
    while(true){
      used.insert(cur.begin(), cur.end());

      result++;
      bool skip = true;
      for(siter iter=cur.begin(), end=cur.end(); iter != end; ++iter){
	ULL n = *iter;
	ULL x = n;
	if(n == 1) skip = false;
	if(n != 1){
	  // power
	  while(MAX_ULL / n >= x && x < ULL(goal)){
	    x *= n;
	    if(x == ULL(goal)) return result;
	    if(used.find(x) == used.end() && x < ULL(goal) + distance){
	      next.insert(x);
	      skip = false;
	      if(goal - x > 0 && goal - x < distance){
		distance = goal - x;
	      }
	      if(x - goal > 0 && x - goal < distance){
		distance = x - goal;
	      }

	    }
	  }
	  
	  // decrement
	  x = n - 1;
	  if(used.find(x) == used.end() && x < ULL(goal) + distance){
	    if(x == ULL(goal)) return result;
	    next.insert(x);
	    if(goal - x > 0 && goal - x < distance){
	      distance = goal - x;
	    }
	    if(x - goal > 0 && x - goal < distance){
	      distance = x - goal;
	    }
	  }
	}
	// increment
	x = n + 1;
	if(used.find(x) == used.end() && x <= goal){
	  if(x == ULL(goal)) return result;
	  next.insert(x);
	  if(goal - x < distance){
	    distance = goal - x;
	  }
	}
      }
      if(skip) return result + distance;
      cur = next;
      next.clear();
    }
  }
||<

*1237918388*[TopCoder] Single Round Match 437 結果
250と500を両方正解して合計で550点取った。

だいぶ回復したけどまだ一軍には戻れない。ぎりぎり点数が足りない。なんか境目あたりにガラスの天井があるように感じる(きっと気のせい)
<img src="http://gyazo.com/f69c4a9a34278cf80896139de756702e.png">

*1237919004*Hacker's cafe Fes
http://d.hatena.ne.jp/akio0911/20090324/p1

Python旅館とかぶっていると思っていたのだけど、Python旅館が12時に終わるので午後から参加できそう。
</body>
```


[はてなダイアリー 2009-03-24](https://nishiohirokazu.hatenadiary.org/archive/2009/03/24)